# Тестовое задание

## Задание 1 <br/>
1. Загрузка файлов

In [1]:
import pandas as pnd

In [2]:
df = pnd.read_csv("dataset_Facebook.csv", sep=";")

Анализ статистических значений для всего массива

In [3]:
df.describe()

C:\Users\evgeniy.botov\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,NaN,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,NaN,NaN,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,NaN,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,NaN,NaN,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,NaN,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,NaN,NaN,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

Медиана

In [4]:
df.median()

Page total likes                                                       129600.0
Category                                                                    2.0
Post Month                                                                  7.0
Post Weekday                                                                4.0
Post Hour                                                                   9.0
Paid                                                                        0.0
Lifetime Post Total Reach                                                5281.0
Lifetime Post Total Impressions                                          9051.0
Lifetime Engaged Users                                                    625.5
Lifetime Post Consumers                                                   551.5
Lifetime Post Consumptions                                                851.0
Lifetime Post Impressions by people who have liked your Page             6255.5
Lifetime Post reach by people who like your Page                         3417.0
Lifetime People who have liked your Page and engaged with your post       412.0
comment                                                                     3.0
like                                                                      101.0
share                                                                      19.0
Total Interactions                                                        123.5
dtype: float64

Мода

In [5]:
df.mode().head(1)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,136393.0,Photo,1.0,10.0,7.0,3.0,0.0,677.0,4372.0,537.0,182.0,431.0,1210.0,690,403.0,0.0,98.0,13.0,0.0

Посмотрим, какие типы записей есть

In [6]:
df["Type"].drop_duplicates()

0      Photo
1     Status
22      Link
29     Video
Name: Type, dtype: object

Анализируем записи по типу <br/>
Фото:

In [7]:
df_photo = df[df["Type"] == "Photo"]

In [8]:
df_photo.describe()

C:\Users\evgeniy.botov\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,426.000000,426.000000,426.000000,426.000000,426.000000,425.000000,426.000000,4.260000e+02,426.000000,426.000000,426.000000,4.260000e+02,426.000000,426.000000,426.000000,425.000000,422.000000,426.000000
mean,122354.171362,1.917840,6.805164,4.107981,7.997653,0.280000,13137.814554,2.899450e+04,818.946009,690.431925,1299.025822,1.642248e+04,6059.103286,507.305164,7.492958,182.611765,27.158768,216.579812
std,16324.528694,0.884007,3.234676,2.056286,4.413082,0.449528,22877.787010,8.095792e+04,868.447092,731.712670,1965.996628,6.450149e+04,7819.018244,399.972665,22.522275,345.245233,44.919679,405.709232
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.000000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.000000,0.000000,0.000000,0.000000
25%,109670.000000,1.000000,4.000000,2.000000,3.000000,NaN,3092.500000,5.390000e+03,399.000000,335.000000,513.000000,3.695250e+03,2100.250000,300.250000,1.000000,NaN,NaN,71.250000
50%,128032.000000,2.000000,7.000000,4.000000,9.000000,NaN,4675.000000,8.118500e+03,605.500000,528.500000,827.000000,5.498000e+03,3110.000000,403.000000,3.000000,NaN,NaN,122.000000
75%,136013.000000,3.000000,10.000000,6.000000,11.000000,NaN,10571.000000,1.701375e+04,949.000000,832.250000,1327.500000,9.823000e+03,5577.000000,569.750000,7.000000,NaN,NaN,225.000000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.000000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,3430.000000,372.000000,5172.000000,790.000000,6334.000000

In [9]:
df_photo.median()

Page total likes                                                       128032.0
Category                                                                    2.0
Post Month                                                                  7.0
Post Weekday                                                                4.0
Post Hour                                                                   9.0
Paid                                                                        0.0
Lifetime Post Total Reach                                                4675.0
Lifetime Post Total Impressions                                          8118.5
Lifetime Engaged Users                                                    605.5
Lifetime Post Consumers                                                   528.5
Lifetime Post Consumptions                                                827.0
Lifetime Post Impressions by people who have liked your Page             5498.0
Lifetime Post reach by people who like your Page                         3110.0
Lifetime People who have liked your Page and engaged with your post       403.0
comment                                                                     3.0
like                                                                      100.0
share                                                                      19.0
Total Interactions                                                        122.0
dtype: float64

In [10]:
df_photo.mode().head(1)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,124940.0,Photo,1.0,10.0,7.0,3.0,0.0,677.0,4372.0,537.0,298.0,431.0,1210.0,690,403.0,0.0,7.0,14.0,0.0

Ссылки:

In [11]:
df_link = df[df["Type"] == "Link"]

In [12]:
df_link.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,116363.181818,1.136364,6.590909,4.272727,5.727273,0.272727,18544.590909,28725.454545,342.818182,292.681818,374.090909,11148.590909,6544.363636,210.545455,2.818182,73.318182,12.909091,89.045455
std,21459.767350,0.467563,4.563406,1.856310,3.930126,0.455842,21399.411331,50042.047711,340.174414,291.385261,358.404787,8888.568907,5960.612461,188.873030,3.633657,85.746240,11.751025,95.720564
min,85979.000000,1.000000,1.000000,1.000000,2.000000,0.000000,1536.000000,3094.000000,24.000000,23.000000,26.000000,2307.000000,1180.000000,19.000000,0.000000,5.000000,0.000000,6.000000
25%,98829.250000,1.000000,3.000000,3.000000,3.000000,0.000000,3878.000000,6861.500000,105.000000,84.750000,120.000000,6367.750000,3156.000000,92.250000,0.000000,19.500000,5.500000,32.750000
50%,115396.000000,1.000000,4.500000,4.500000,4.000000,0.000000,7422.000000,9773.000000,244.000000,205.000000,290.000000,9034.500000,5039.000000,161.500000,1.500000,37.000000,10.500000,52.500000
75%,138059.000000,1.000000,11.750000,6.000000,9.250000,0.750000,30938.000000,26153.750000,422.000000,355.750000,472.750000,13903.750000,8140.000000,251.750000,4.000000,110.750000,15.000000,125.000000
max,138895.000000,3.000000,12.000000,7.000000,14.000000,1.000000,70912.000000,229733.000000,1374.000000,1106.000000,1345.000000,42338.000000,27232.000000,788.000000,15.000000,379.000000,44.000000,420.000000

In [13]:
df_photo.median()

Page total likes                                                       128032.0
Category                                                                    2.0
Post Month                                                                  7.0
Post Weekday                                                                4.0
Post Hour                                                                   9.0
Paid                                                                        0.0
Lifetime Post Total Reach                                                4675.0
Lifetime Post Total Impressions                                          8118.5
Lifetime Engaged Users                                                    605.5
Lifetime Post Consumers                                                   528.5
Lifetime Post Consumptions                                                827.0
Lifetime Post Impressions by people who have liked your Page             5498.0
Lifetime Post reach by people who like your Page                         3110.0
Lifetime People who have liked your Page and engaged with your post       403.0
comment                                                                     3.0
like                                                                      100.0
share                                                                      19.0
Total Interactions                                                        122.0
dtype: float64

In [14]:
df_photo.mode().head(1)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,124940.0,Photo,1.0,10.0,7.0,3.0,0.0,677.0,4372.0,537.0,298.0,431.0,1210.0,690,403.0,0.0,7.0,14.0,0.0

Статус

In [15]:
df_status = df[df["Type"] == "Status"]

In [16]:
df_status.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
mean,132647.044444,2.022222,9.066667,4.577778,7.244444,0.222222,13078.888889,24244.466667,2040.222222,1949.555556,2838.866667,18664.266667,9908.577778,1719.844444,8.911111,176.711111,31.422222,217.044444
std,7902.145290,0.398228,2.553073,1.924588,3.926342,0.420437,5218.086371,9929.142874,1351.996838,1319.980433,2075.419548,7521.069017,3997.608572,1083.684581,12.451400,150.772499,24.272589,178.479940
min,104070.000000,1.000000,3.000000,1.000000,2.000000,0.000000,3930.000000,7509.000000,128.000000,86.000000,112.000000,5009.000000,2410.000000,101.000000,0.000000,13.000000,1.000000,17.000000
25%,131300.000000,2.000000,7.000000,3.000000,3.000000,0.000000,9232.000000,17099.000000,1151.000000,1073.000000,1512.000000,13887.000000,7360.000000,995.000000,2.000000,86.000000,16.000000,106.000000
50%,135713.000000,2.000000,10.000000,5.000000,9.000000,0.000000,11096.000000,20849.000000,1701.000000,1599.000000,2201.000000,17502.000000,8980.000000,1604.000000,4.000000,150.000000,28.000000,186.000000
75%,138353.000000,2.000000,12.000000,6.000000,10.000000,0.000000,15816.000000,30514.000000,2675.000000,2567.000000,3420.000000,22103.000000,11792.000000,2256.000000,10.000000,226.000000,39.000000,265.000000
max,139441.000000,3.000000,12.000000,7.000000,15.000000,1.000000,31136.000000,59964.000000,6164.000000,5934.000000,9237.000000,37849.000000,21352.000000,4376.000000,60.000000,859.000000,123.000000,1009.000000

In [17]:
df_status.median()

Page total likes                                                       135713.0
Category                                                                    2.0
Post Month                                                                 10.0
Post Weekday                                                                5.0
Post Hour                                                                   9.0
Paid                                                                        0.0
Lifetime Post Total Reach                                               11096.0
Lifetime Post Total Impressions                                         20849.0
Lifetime Engaged Users                                                   1701.0
Lifetime Post Consumers                                                  1599.0
Lifetime Post Consumptions                                               2201.0
Lifetime Post Impressions by people who have liked your Page            17502.0
Lifetime Post reach by people who like your Page                         8980.0
Lifetime People who have liked your Page and engaged with your post      1604.0
comment                                                                     4.0
like                                                                      150.0
share                                                                      28.0
Total Interactions                                                        186.0
dtype: float64

In [18]:
df_status.mode().head(1)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441.0,Status,2.0,12.0,5.0,10.0,0.0,NaN,NaN,NaN,NaN,1692.0,NaN,NaN,NaN,2.0,86.0,1.0,117.0

Видео:

In [19]:
df_video = df[df["Type"] == "Video"]

In [20]:
df_video.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,7.000000,7.0,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.00000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,135014.857143,1.0,9.571429,3.571429,8.714286,0.571429,51205.714286,102622.428571,1707.00000,1584.714286,2600.142857,43149.857143,17386.285714,979.428571,12.285714,231.428571,52.142857,295.857143
std,4730.551709,0.0,2.299068,1.511858,4.347961,0.534522,48825.191031,101838.314111,1174.78608,1160.701471,2296.643524,31072.683306,9861.583607,650.805362,8.693183,142.025652,42.643595,183.992236
min,126424.000000,1.0,6.000000,2.000000,2.000000,0.000000,13544.000000,30235.000000,459.00000,411.000000,539.000000,21436.000000,9568.000000,363.000000,2.000000,65.000000,13.000000,81.000000
25%,132835.000000,1.0,8.000000,2.500000,6.500000,0.000000,19144.000000,36181.500000,829.00000,763.000000,1197.500000,25644.500000,12340.000000,503.000000,4.000000,121.000000,13.500000,144.000000
50%,137893.000000,1.0,11.000000,3.000000,11.000000,1.000000,30624.000000,56950.000000,1779.00000,1643.000000,2331.000000,30131.000000,14112.000000,885.000000,17.000000,204.000000,44.000000,271.000000
75%,138111.000000,1.0,11.000000,4.500000,11.000000,1.000000,68488.000000,140854.500000,2090.50000,1845.500000,2804.500000,45845.500000,17312.000000,1192.000000,18.000000,330.000000,80.000000,440.500000
max,138895.000000,1.0,12.000000,6.000000,13.000000,1.000000,139008.000000,277100.000000,3872.00000,3822.000000,7327.000000,107502.000000,38720.000000,2218.000000,23.000000,449.000000,121.000000,550.000000

In [21]:
df_video.median()

Page total likes                                                       137893.0
Category                                                                    1.0
Post Month                                                                 11.0
Post Weekday                                                                3.0
Post Hour                                                                  11.0
Paid                                                                        1.0
Lifetime Post Total Reach                                               30624.0
Lifetime Post Total Impressions                                         56950.0
Lifetime Engaged Users                                                   1779.0
Lifetime Post Consumers                                                  1643.0
Lifetime Post Consumptions                                               2331.0
Lifetime Post Impressions by people who have liked your Page            30131.0
Lifetime Post reach by people who like your Page                        14112.0
Lifetime People who have liked your Page and engaged with your post       885.0
comment                                                                    17.0
like                                                                      204.0
share                                                                      44.0
Total Interactions                                                        271.0
dtype: float64

In [22]:
df_video.mode().head(1)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,137893.0,Video,1.0,11.0,2,11.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,13.0,NaN

## Поиск самого популярного объекта

Из описания датасета следует, что признак Total Interactions -- сумма количества лайков, репостов и комментариев к записи. Поскольку в задании не было четкого определения популярности, я буду считать самым популярным объектом тот, для которого Total Interactions максимально

In [28]:
df_total = df["Total Interactions"]
df.loc[df_total.idxmax()]

Page total likes                                                       130791
Type                                                                    Photo
Category                                                                    2
Post Month                                                                  7
Post Weekday                                                                3
Post Hour                                                                   5
Paid                                                                        1
Lifetime Post Total Reach                                              180480
Lifetime Post Total Impressions                                        319133
Lifetime Engaged Users                                                   8072
Lifetime Post Consumers                                                  4010
Lifetime Post Consumptions                                               6242
Lifetime Post Impressions by people who have liked your Page           108752
Lifetime Post reach by people who like your Page                        51456
Lifetime People who have liked your Page and engaged with your post      3316
comment                                                                   372
like                                                                     5172
share                                                                     790
Total Interactions                                                       6334
Name: 244, dtype: object

Объяснить популярность именно этой записи можно тем, что его продвижение было оплачено (Paid=1), он принадлежит ко 2 категории (судя по описанию, это категория Product -- описание продукта производителя, что представляет наибольший интерес для подписчиков группы), а также он был сделан утром в среду, когда все перед работой обновляют ленту в Фейсбуке